name: Upload Download Artifacts

on:
  pull_request:
    types: [ labeled ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get App Installation Token
        uses: tibdex/github-app-token@v1
        with: 
          app_id: 295785
          installation_id: 39974503
          private_key: ${{ secrets.APP_CLIENT_TOKEN }}
      - name: Run a one-line script
        run: |
          mkdir haha
          echo "hello world" > haha/a.txt
          echo "hehehehehehe" > haha/b.txt
          echo "hahahahaha" > haha/c.txt
      - uses: actions/upload-artifact@v3
        with:
          name: i-dont-know
          path: |
            haha/a.txt
            haha/b.txt
      - uses: actions/upload-artifact@v3
        with:
          name: i-do-know
          path: |
            haha/c.txt
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
      - run: |
          ls -al
          ls -al haha
          ls -al i-dont-know
          ls -al i-do-know
          ls -al i-dont-know/haha
